web:
  build: .
  ports:
    - "3000:3000"
  environment:
    RAILS_ENV: production
    RAILS_SERVE_STATIC_FILES: 'true'
    RAILS_LOG_TO_STDOUT: 'true'
    SECRET_KEY_BASE: dummy
    DATABASE_HOST: '192.168.0.148'
    DATABASE_PORT: '5432'
    DATABASE_USERNAME: 'db_username'
    DATABASE_PASSWORD: 'db_password'
    DATABASE_NAME: 'journal_production'
    ADMIN_LOGIN: root
    ADMIN_PASSWORD: whoami
    SMS_API_KEY: 'xxxxxxxxxxx'

